<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Upload Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'tulis.space@gmail.com',
		'to' => 'tulis.space@gmail.com'
	),
	'fields' => array(
		'custom_U42954' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Full Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Full Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Pen Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Pen Name\' is required.',
				'format' => 'Field \'Pen Name\' has an invalid email.'
			)
		),
		'custom_U42941' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.'
			)
		),
		'custom_U42926' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Message',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Message\' is required.'
			)
		),
		'custom_U42932' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Writings Title',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Writings Title\' is required.'
			)
		),
		'custom_U42945' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'Writing Categories',
			'required' => true,
			'optionItems' => array(
				'Poems',
				'Short Story'
			),
			'errors' => array(
				'required' => 'Field \'Writing Categories\' is required.',
				'format' => 'Field \'Writing Categories\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
